# .github/workflows/release.yml
name: RELEASE

on:
  release:
    types: [created]
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-apple-darwin
            archive: zip
    steps:
      - name: Set Up
        run: export PKG_CONFIG_PATH=/usr/share/pkgconfig:/usr/lib/x86_64-apple-darwin/pkgconfig;

      - uses: actions/checkout@master
      - name: Compile and release
        run: rust-build/rust-build.action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
